<span id="<?php
    echo $this->getOption('id_prefix','li');
    if($this->useValueAsId('li')): echo str_replace(' ','',$item->getValue()); else: echo $item->getID(); endif;
?>" class="<?php if ($liclasses): echo ' '.$liclasses; endif; ?>">
<?php if($item->hasLink()): ?><a<?php if(!$item->hasChildren()):?> aria-current="page"<?php endif; ?> class="<?php if ($aclasses): echo ' '.$aclasses; endif; ?>" href="<?php echo $item->getLink() ?>"><?php endif; ?>
<?php echo $item->getValue() ?>
<?php if($item->is_current): ?> <span class="sr-only">(current)</span><?php endif; ?>
<?php if($item->hasLink()): ?></a><?php endif; ?>
</span>
