<li id="<?php
    echo $this->getOption('id_prefix','li');
    if($this->useValueAsId('li')): echo str_replace(' ','',$item->getValue()); else: echo $item->getID(); endif;
?>" class="breadcrumb-item<?php if ($liclasses): echo ' '.$liclasses; endif; if ($item->is_current): echo ' active'; endif;?>"<?php if($item->is_current): ?> aria-current="page"<?php endif; ?>>
<?php if($item->hasLink() && !$item->is_current): ?><a class="<?php if ($aclasses): echo ' '.$aclasses; endif; ?>" href="<?php echo $item->getLink() ?>"><?php endif; ?>
<?php echo $item->getValue() ?>
<?php if($item->is_current): ?> <span class="sr-only">(current)</span><?php endif; ?>
<?php if($item->hasLink() && !$item->is_current): ?></a><?php endif; ?>
</li>
